<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Compile Include="..\PandaLcarsTactical\Weather\*.cs" Link="Weather\%(Filename)%(Extension)" /><Compile Include="..\PandaLcarsTactical\SystemInfo\*.cs" Link="SystemInfo\%(Filename)%(Extension)" /><Compile Include="..\PandaLcarsTactical\QuickLaunch\LinkStore.cs" Link="LinkStore.cs" /><Compile Include="..\PandaLcarsTactical\Settings\PersonalServices.cs" Link="PersonalServices.cs" /></ItemGroup></Project>

